### PR TITLE
Support errors in object and array values

### PR DESCRIPTION
**Pull request by voldern**
Support errors in object and array values by supporting names with paths like `variants.0.name`.

### CODE REVIEW

**Comment by justinobney** [comment]
Can you provide a test case? Or a codesandbox?

**Comment by voldern** [comment]
Thank you for the feedback. Added a test case.

**Comment by justinobney** [comment]
@voldern I will create a realease shortly. Thanks!

**Comment by justinobney** [comment]
@voldern deployed!

**Comment by voldern** [comment]
Thank you for the quick merge and release :bowing_man:

**Pull request merged**
